version: '3'

services:
  api-prodescriber:
    build: .
    entrypoint: sh ./.docker/entrypoint.sh
    container_name: prodescriber
    ports:
      - 3002:3002
    volumes:
      - ./:/home/prodescriber_api/app
    tty: true
    networks:
      - prodescriber-network

  db:
    image: mongo:4.4
    container_name: mongo-db
    volumes:
      - /mongodb/dbdata:/data/db
      - /mongodb/configdb:/data/configdb
    environment:
      #      MONGO_INITDB_ROOT_USERNAME: root
      #      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: prodescriber
    networks:
      - prodescriber-network

networks:
  prodescriber-network:
    driver: bridge
